In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../docs/centres.csv')

In [29]:
print ("{} organisations are participating".format(df.Organisation.count()))
print ("{} site visits have taken place".format(len(df[df.SIV == 'Y'])))
print ("{} C&Cs have been recieved".format(len(df[df['C&C'] == 'Y'])))
print ("{} centres have recruited at least one participant".format(len(df[df['Recruiting'] == 'Y'])))

19 organisations are participating
13 site visits have taken place
12 C&Cs have been recieved
5 centres have recruited at least one participant

In [30]:
df

,Organisation,Centre ID,SIV,C&C,Recruiting
0,Heart of England NHS Foundation Trust,1,Y,Y,N
1,Morriston Hospital,2,Y,Y,N
2,Imperial College Healthcare NHS Trust,10,Y,Y,Y
3,Nottingham University Hospitals NHS Trust,3,Y,Y,N
4,Southampton University Hospitals NHS Trust,4,Y,N,N
5,University Hospital of South Manchester,5,Y,Y,Y
6,Papworth Hospital NHS Foundation Trust,6,N,N,N
7,Royal Devon and Exeter NHS Foundation Trust,7,Y,Y,N
8,Aintree University Hospitals NHS Foundation Trust,8,Y,Y,Y
9,North Bristol NHS Trust,9,Y,Y,Y
10,Aberdeen Royal Infirmary,11,Y,Y,Y
11,Glasgow Royal Infirmary,12,Y,Y,N
12,Royal Infirmary of Edinburgh,13,Y,Y,N
13,The Newcastle Upon Tyne Hospitals NHS Foundati...,14,N,N,N
14,Taunton and Somerset NHS Foundation Trust,15,Y,Y,N
15,Leeds Teaching Hospitals NHS Trust,16,N,N,N
16,Portsmouth Hospitals NHS Trust,17,N,N,N
17,University Hospitals Birmingham NHS Foundation...,18,N,N,N
18,Worcestershire Acute Hospitals NHS Trust,19,N,N,N